// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.1
// source: operator.proto

package operator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Types int32

const (
	Types_None     Types = 0  //无意义
	Types_Add      Types = 1  //添加
	Types_Sub      Types = 2  //扣除
	Types_Set      Types = 3  //set
	Types_Del      Types = 4  //del
	Types_New      Types = 5  //新对象
	Types_Max      Types = 10 //最大值写入，最终转换成set或者drop
	Types_Min      Types = 11 //最小值写入，最终转换成set或者drop
	Types_Drop     Types = 90 //抛弃不执行任何操作
	Types_Resolve  Types = 91 //自动分解
	Types_Overflow Types = 92 //道具已满使用其他方式(邮件)转发
)

// Enum value maps for Types.
var (
	Types_name = map[int32]string{
		0:  "None",
		1:  "Add",
		2:  "Sub",
		3:  "Set",
		4:  "Del",
		5:  "New",
		10: "Max",
		11: "Min",
		90: "Drop",
		91: "Resolve",
		92: "Overflow",
	}
	Types_value = map[string]int32{
		"None":     0,
		"Add":      1,
		"Sub":      2,
		"Set":      3,
		"Del":      4,
		"New":      5,
		"Max":      10,
		"Min":      11,
		"Drop":     90,
		"Resolve":  91,
		"Overflow": 92,
	}
)

func (x Types) Enum() *Types {
	p := new(Types)
	*p = x
	return p
}

func (x Types) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Types) Descriptor() protoreflect.EnumDescriptor {
	return file_operator_proto_enumTypes[0].Descriptor()
}

func (Types) Type() protoreflect.EnumType {
	return &file_operator_proto_enumTypes[0]
}

func (x Types) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Types.Descriptor instead.
func (Types) EnumDescriptor() ([]byte, []int) {
	return file_operator_proto_rawDescGZIP(), []int{0}
}

type Operator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OID    string `protobuf:"bytes,1,opt,name=OID,json=o, omitempty,proto3" json:"OID,omitempty"`
	IID    int32  `protobuf:"varint,2,opt,name=IID,json=i, omitempty,proto3" json:"IID,omitempty"`
	Key    string `protobuf:"bytes,3,opt,name=Key,json=k, omitempty,proto3" json:"Key,omitempty"`
	Type   Types  `protobuf:"varint,4,opt,name=Type,json=t, omitempty,proto3,enum=Types" json:"Type,omitempty"`
	Value  int64  `protobuf:"varint,5,opt,name=Value,json=v, omitempty,proto3" json:"Value,omitempty"`
	Result []byte `protobuf:"bytes,6,opt,name=Result,json=r, omitempty,proto3" json:"Result,omitempty"`
}

func (x *Operator) Reset() {
	*x = Operator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Operator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operator) ProtoMessage() {}

func (x *Operator) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operator.ProtoReflect.Descriptor instead.
func (*Operator) Descriptor() ([]byte, []int) {
	return file_operator_proto_rawDescGZIP(), []int{0}
}

func (x *Operator) GetOID() string {
	if x != nil {
		return x.OID
	}
	return ""
}

func (x *Operator) GetIID() int32 {
	if x != nil {
		return x.IID
	}
	return 0
}

func (x *Operator) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Operator) GetType() Types {
	if x != nil {
		return x.Type
	}
	return Types_None
}

func (x *Operator) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Operator) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_operator_proto protoreflect.FileDescriptor

var file_operator_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xba, 0x01, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x19, 0x0a,
	0x03, 0x4f, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x2c, 0x20, 0x6f,
	0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x19, 0x0a, 0x03, 0x49, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x69, 0x2c, 0x20, 0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x19, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x6b, 0x2c, 0x20, 0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x22,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x06, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x52, 0x0c, 0x74, 0x2c, 0x20, 0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x1b, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x76, 0x2c, 0x20, 0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x1c, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x72, 0x2c, 0x20, 0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2a, 0x75, 0x0a,
	0x05, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x75, 0x62,
	0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x44,
	0x65, 0x6c, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x65, 0x77, 0x10, 0x05, 0x12, 0x07, 0x0a,
	0x03, 0x4d, 0x61, 0x78, 0x10, 0x0a, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x69, 0x6e, 0x10, 0x0b, 0x12,
	0x08, 0x0a, 0x04, 0x44, 0x72, 0x6f, 0x70, 0x10, 0x5a, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x10, 0x5b, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x76, 0x65, 0x72, 0x66, 0x6c,
	0x6f, 0x77, 0x10, 0x5c, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_operator_proto_rawDescOnce sync.Once
	file_operator_proto_rawDescData = file_operator_proto_rawDesc
)

func file_operator_proto_rawDescGZIP() []byte {
	file_operator_proto_rawDescOnce.Do(func() {
		file_operator_proto_rawDescData = protoimpl.X.CompressGZIP(file_operator_proto_rawDescData)
	})
	return file_operator_proto_rawDescData
}

var file_operator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_operator_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_operator_proto_goTypes = []interface{}{
	(Types)(0),       // 0: Types
	(*Operator)(nil), // 1: Operator
}
var file_operator_proto_depIdxs = []int32{
	0, // 0: Operator.Type:type_name -> Types
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_operator_proto_init() }
func file_operator_proto_init() {
	if File_operator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_operator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Operator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_operator_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_operator_proto_goTypes,
		DependencyIndexes: file_operator_proto_depIdxs,
		EnumInfos:         file_operator_proto_enumTypes,
		MessageInfos:      file_operator_proto_msgTypes,
	}.Build()
	File_operator_proto = out.File
	file_operator_proto_rawDesc = nil
	file_operator_proto_goTypes = nil
	file_operator_proto_depIdxs = nil
}
